services:
  iotdb-datanode:
    image: apache/iotdb:2.0.6-datanode
    container_name: iotdb-datanode
    restart: always
    depends_on:
      iotdb-confignode:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "ls", "/iotdb/data/datanode/system"]
      interval: 10s
      timeout: 60s
      retries: 30
      start_period: 30s
    ports:
      - "6667:6667"
    networks:
      - iotdb-network
    environment:
      - dn_rpc_address=iotdb-datanode
      - dn_internal_address=iotdb-datanode
      - dn_seed_config_node=iotdb-confignode:10710
      - IOTDB_JMX_OPTS=-Xms768M -Xmx768M -XX:MaxDirectMemorySize=384M
      - CONFIGNODE_JMX_OPTS=-Xms384M -Xmx384M -XX:MaxDirectMemorySize=192M

  iotdb-confignode:
    image: apache/iotdb:2.0.6-confignode
    container_name: iotdb-confignode
    restart: always
    healthcheck:
      test: ["CMD", "ls", "/iotdb/data"]
      interval: 3s
      timeout: 5s
      retries: 30
      start_period: 30s
    networks:
      - iotdb-network
    environment:
      - cn_internal_address=iotdb-confignode
      - cn_internal_port=10710
      - cn_seed_config_node=iotdb-confignode:10710
      - IOTDB_JMX_OPTS=-Xms384M -Xmx384M -XX:MaxDirectMemorySize=192M
      - CONFIGNODE_JMX_OPTS=-Xms384M -Xmx384M -XX:MaxDirectMemorySize=192M

networks:
  iotdb-network:
    driver: bridge
